package com.lbo;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.lbo.foursquare.Response;
import com.lbo.foursquare.model.Checkin;
import com.lbo.foursquare.response.FriendsResponse;
import com.lbo.foursquare.response.ListResponse;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.lang.reflect.Type;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

/**
 * @author lbouin
 */
public class ListTest {

    private BufferedReader in = null;

    @Before
    public void setup()
            throws IOException
    {
        in = new BufferedReader(
                new InputStreamReader(getClass().getResourceAsStream("/list.json")));
    }

    @After
    public void teardown()
            throws IOException
    {
        if (in != null)
        {
            in.close();
        }
        in = null;

    }

    @Test
    public void basic(){

        JsonReader reader = new JsonReader(in);

        Type listResponseType = new TypeToken<Response<ListResponse>>() {}.getType();
        Response<ListResponse> result = new Gson().fromJson(reader,  listResponseType);

        assertTrue(result.isOK());

        assertEquals("506e10d6e4b082a2a956a719",result.response.list.id);
        assertEquals("My wine's spot",result.response.list.name);
        assertEquals("Generated by The Winestersquare",result.response.list.description);
        assertEquals("https://foursquare.com/laurentbouin/list/my-wines-spot",result.response.list.url);

    }

}
